[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs_18", "nodePackages.npm"]

[phases.install]
cmds = ["pip install --break-system-packages -r requirements.txt"]

[phases.build]
cmds = ["npm ci"]

[start]
cmd = "gunicorn server:app -c gunicorn.conf.py --log-level debug --capture-output --enable-stdio-inheritance" 