[phases.setup]
nixPkgs = [
    "python311", 
    "python311Packages.pip",
    "zlib",
    "zlib.dev",
    "postgresql_15",
    "postgresql_15.lib",
    "openssl",
    "pkg-config"
]

[phases.install]
cmds = [
    "pip install --break-system-packages -r requirements.txt"
]

[variables]
LD_LIBRARY_PATH = "/nix/store/*-zlib-*/lib:/nix/store/*-postgresql-*/lib:$LD_LIBRARY_PATH"

[start]
# Smart start command that detects cron jobs vs web deployment
cmd = "python smart_start.py" 