[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install --break-system-packages -r requirements.txt"]

[start]
# Smart start command that detects cron jobs vs web deployment
cmd = "python smart_start.py" 