[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.venv"]

[phases.install]
cmds = [
    "python -m venv /app/venv",
    "source /app/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = ["npm ci"]

[start]
cmd = "source /app/venv/bin/activate && gunicorn server:app -c gunicorn.conf.py --log-level debug --capture-output --enable-stdio-inheritance" 