[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]
aptPkgs = ["libpq-dev", "zlib1g-dev", "postgresql-client", "build-essential", "pkg-config"]

[phases.install]
cmds = [
    "pip install --break-system-packages --force-reinstall --no-cache-dir psycopg2-binary",
    "pip install --break-system-packages -r requirements.txt"
]

[start]
# Smart start command that detects cron jobs vs web deployment  
cmd = "python smart_start.py" 