[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "postgresql.lib", "openssl", "postgresql_15", "zlib", "pkgconfig"]

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install --break-system-packages --no-cache-dir --timeout=300 --retries=5 psycopg2-binary",
    "pip install --break-system-packages --no-cache-dir --timeout=300 --retries=5 -r requirements.txt"
]

[start]
# Use production server for Railway deployment
cmd = "python production_server.py" 