[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn server:app -c gunicorn.conf.py"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

# ETL Cron Job Service
[deploy.cronJobs.etl_import]
schedule = "0 2 * * *"  # Daily at 2 AM UTC
command = "python scripts/railway_cron_etl.py"

# Optional: Weekly full import (more comprehensive)
[deploy.cronJobs.weekly_etl]
schedule = "0 3 * * 0"  # Weekly on Sunday at 3 AM UTC
command = "python scripts/railway_cron_etl.py --full-import"

[env]
FLASK_ENV = "production"
DISABLE_SELENIUM = "true"
PYTHONUNBUFFERED = "1"
WEB_CONCURRENCY = "1"
SESSION_COOKIE_DOMAIN = ".lovetorally.com"
PGCONNECT_TIMEOUT = "60"
PGPOOL_MIN_CONNECTIONS = "1"
PGPOOL_MAX_CONNECTIONS = "20" 