[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

# Production ETL Cron Job Services - Direct entry_cron.py execution  
[deploy.cronJobs.etl_import]
schedule = "0 2 * * *"  # Daily at 2 AM UTC
command = "cd /app && FIX_CONSTRAINTS=false python entry_cron.py"
# Explicitly disable constraint fix mode to run full ETL pipeline

# Optional: Weekly full import (more comprehensive)
[deploy.cronJobs.weekly_etl]
schedule = "0 3 * * 0"  # Weekly on Sunday at 3 AM UTC  
command = "cd /app && FIX_CONSTRAINTS=false python entry_cron.py"
# Explicitly disable constraint fix mode to run full ETL pipeline

# Staging ETL Cron Job Services (for testing fresh JSON imports)
[deploy.cronJobs.staging_etl_import]
schedule = "0 */4 * * *"  # Every 4 hours instead of every 30 minutes
command = "CRON_JOB_MODE=true FLASK_APP='' python data/etl/database_import/master_import.py --league aptachicago"

[deploy.cronJobs.staging_etl_full]
schedule = "0 8 * * *"  # Daily at 8 AM UTC instead of every 6 hours
command = "CRON_JOB_MODE=true FLASK_APP='' python data/etl/database_import/master_import.py"

# CNSWPL Scraper Runner - Full scrape and import for CNSWPL league
[deploy.cronJobs.cnswpl_scraper]
schedule = "0 15 * * 1,2,6"  # Monday, Tuesday, Saturday at 3 PM UTC (9 AM Central)
command = "python3 data/cron/cnswpl_scraper_runner.py"

# APTA All Scraper - Wednesday, Thursday, Friday at 5 AM Central (11 AM UTC CST)
[deploy.cronJobs.apta_all_scraper]
schedule = "0 11 * * 3,4,5"
command = "python3 data/cron/apta_scraper_runner_all.py"

# APTA Stats/Scores Scraper - Wednesday, Thursday, Friday at 12 PM Central (6 PM UTC CST)
[deploy.cronJobs.apta_stats_scores_scraper]
schedule = "0 18 * * 3,4,5"
command = "python3 data/cron/apta_scraper_runner_stats_scores.py"

[env]
FLASK_ENV = "production"
DISABLE_SELENIUM = "true"
PYTHONUNBUFFERED = "1"
WEB_CONCURRENCY = "1"
SESSION_COOKIE_DOMAIN = ".lovetorally.com"
PGCONNECT_TIMEOUT = "60"
PGPOOL_MIN_CONNECTIONS = "1"
PGPOOL_MAX_CONNECTIONS = "20"
# Cron job environment variables (set by individual cron jobs)
CRON_JOB_MODE = "false"  # Default to false for web server, overridden by cron scripts 