[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health-minimal"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

# Production ETL Cron Job Services
[deploy.cronJobs.etl_import]
schedule = "0 2 * * *"  # Daily at 2 AM UTC
command = "python cronjobs/run_pipeline.py"

# Optional: Weekly full import (more comprehensive)
[deploy.cronJobs.weekly_etl]
schedule = "0 3 * * 0"  # Weekly on Sunday at 3 AM UTC
command = "python cronjobs/run_pipeline.py"

# Staging ETL Cron Job Services (for testing fresh JSON imports)
[deploy.cronJobs.staging_etl_import]
schedule = "0 */4 * * *"  # Every 4 hours instead of every 30 minutes
command = "python data/etl/database_import/master_import.py --league aptachicago"

[deploy.cronJobs.staging_etl_full]
schedule = "0 8 * * *"  # Daily at 8 AM UTC instead of every 6 hours
command = "python data/etl/database_import/master_import.py"

[env]
FLASK_ENV = "production"
DISABLE_SELENIUM = "true"
PYTHONUNBUFFERED = "1"
WEB_CONCURRENCY = "1"
SESSION_COOKIE_DOMAIN = ".lovetorally.com"
PGCONNECT_TIMEOUT = "60"
PGPOOL_MIN_CONNECTIONS = "1"
PGPOOL_MAX_CONNECTIONS = "20" 