[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn --worker-class eventlet -w 1 server:app"
healthcheckPath = "/login"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[env]
FLASK_ENV = "production"
DISABLE_SELENIUM = "true"
PYTHONUNBUFFERED = "1" 