[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn server:app -c gunicorn.conf.py"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[env]
FLASK_ENV = "production"
DISABLE_SELENIUM = "true"
PYTHONUNBUFFERED = "1"
WEB_CONCURRENCY = "1"
SESSION_COOKIE_DOMAIN = ".lovetorally.com"
PGCONNECT_TIMEOUT = "60"
PGPOOL_MIN_CONNECTIONS = "1"
PGPOOL_MAX_CONNECTIONS = "20" 