[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

# Production ETL Cron Job Services - Direct entry_cron.py execution  
[deploy.cronJobs.etl_import]
schedule = "0 2 * * *"  # Daily at 2 AM UTC
command = "cd /app && python entry_cron.py"
# Absolute paths to ensure Railway uses correct script

# Optional: Weekly full import (more comprehensive)
[deploy.cronJobs.weekly_etl]
schedule = "0 3 * * 0"  # Weekly on Sunday at 3 AM UTC  
command = "cd /app && python entry_cron.py"
# Absolute paths to ensure Railway uses correct script

# Staging ETL Cron Job Services (for testing fresh JSON imports)
[deploy.cronJobs.staging_etl_import]
schedule = "0 */4 * * *"  # Every 4 hours instead of every 30 minutes
command = "CRON_JOB_MODE=true FLASK_APP='' python data/etl/database_import/master_import.py --league aptachicago"

[deploy.cronJobs.staging_etl_full]
schedule = "0 8 * * *"  # Daily at 8 AM UTC instead of every 6 hours
command = "CRON_JOB_MODE=true FLASK_APP='' python data/etl/database_import/master_import.py"

[env]
FLASK_ENV = "production"
DISABLE_SELENIUM = "true"
PYTHONUNBUFFERED = "1"
WEB_CONCURRENCY = "1"
SESSION_COOKIE_DOMAIN = ".lovetorally.com"
PGCONNECT_TIMEOUT = "60"
PGPOOL_MIN_CONNECTIONS = "1"
PGPOOL_MAX_CONNECTIONS = "20"
# Cron job environment variables (set by individual cron jobs)
CRON_JOB_MODE = "false"  # Default to false for web server, overridden by cron scripts 