#!/bin/bash
# Simple script to check Railway volume for CNSWPL JSON files

echo "======================================================================"
echo "Checking Railway Volume: CNSWPL_Scraper_Volume"
echo "======================================================================"
echo ""
echo "This script will help you check if the scraped JSON files exist"
echo "in the Railway volume."
echo ""
echo "⚠️  You need to be logged into Railway CLI first:"
echo "    railway login"
echo ""
echo "======================================================================"
echo "Step 1: Find your CNSWPL service name"
echo "======================================================================"
echo ""
echo "Run this command to see your services:"
echo "  railway status"
echo ""
read -p "Press Enter to continue or Ctrl+C to exit..."
echo ""
echo "======================================================================"
echo "Step 2: SSH into the service"
echo "======================================================================"
echo ""
echo "Replace <SERVICE_NAME> with your actual service name:"
echo "  railway shell --service <SERVICE_NAME>"
echo ""
echo "Common service names:"
echo "  - CNSWPL_Cron_Service"
echo "  - CNSWPL_Cron_Service_Production"
echo "  - CNSWPL_Cron_Service_Staging"
echo ""
read -p "Press Enter when ready to continue..."
echo ""
echo "======================================================================"
echo "Step 3: Once inside SSH, run these commands:"
echo "======================================================================"
echo ""
echo "# Check if CNSWPL_CRON_VARIABLE is set:"
echo "  echo \$CNSWPL_CRON_VARIABLE"
echo ""
echo "# If set to /app/data/leagues, check volume files:"
echo "  ls -lh /app/data/leagues/CNSWPL/*.json 2>/dev/null || echo 'Files not found in /app/data/leagues/CNSWPL/'"
echo ""
echo "# Check file sizes (if files exist):"
echo "  ls -lh /app/data/leagues/CNSWPL/match_scores.json 2>/dev/null && wc -l /app/data/leagues/CNSWPL/match_scores.json 2>/dev/null"
echo ""
echo "# If CNSWPL_CRON_VARIABLE is NOT set, check default location:"
echo "  ls -lh data/leagues/CNSWPL/*.json 2>/dev/null || echo 'Files not found in data/leagues/CNSWPL/'"
echo ""
echo "# Verify what path the scraper would use:"
echo "  python3 -c \"from data.etl.utils.league_directory_manager import get_league_file_path; print('Scraper path:', get_league_file_path('cnswpl', 'match_scores.json'))\""
echo ""
echo "# Verify what path the import would use (AFTER fix):"
echo "  python3 -c \"from data.etl.utils.league_directory_manager import get_league_file_path; print('Import path:', get_league_file_path('CNSWPL', 'match_scores.json'))\""
echo ""
echo "======================================================================"
echo "Expected Results"
echo "======================================================================"
echo ""
echo "✅ If files exist in volume, you should see:"
echo "   - match_scores.json (should be > 1MB, recent timestamp)"
echo "   - players.json"
echo "   - series_stats.json"
echo ""
echo "❌ If files don't exist:"
echo "   - They may have been saved to ephemeral filesystem (lost on restart)"
echo "   - CNSWPL_CRON_VARIABLE may not be set correctly"
echo "   - Volume may not be mounted at /app/data"
echo ""
echo "======================================================================"
echo ""
echo "💡 Tip: Look for recent file timestamps matching when the scraper ran"


