#!/bin/bash
# Commands to run manually via SSH on staging server

echo "=== STAGING DATABASE CLEANUP COMMANDS ==="
echo ""
echo "1. SSH into staging server:"
echo "   ssh rally-staging.up.railway.app"
echo ""
echo "2. Check current match_scores count:"
echo "   psql \$DATABASE_URL -c \"SELECT COUNT(*) FROM match_scores;\""
echo ""
echo "3. Clear match_scores table:"
echo "   psql \$DATABASE_URL -c \"DELETE FROM match_scores;\""
echo ""
echo "4. Run ETL import:"
echo "   cd /app"
echo "   python data/etl/database_import/import_all_jsons_to_database.py"
echo ""
echo "5. Verify the fix:"
echo "   psql \$DATABASE_URL -c \"SELECT COUNT(*) FROM match_scores;\""
echo ""
echo "6. Check Ross Freedman's matches:"
echo "   psql \$DATABASE_URL -c \""
echo "   SELECT "
echo "       p.first_name,"
echo "       p.last_name,"
echo "       p.tenniscores_player_id,"
echo "       COUNT(ms.id) as total_matches,"
echo "       COUNT(CASE WHEN ms.match_date >= '2024-08-01' AND ms.match_date <= '2025-03-31' THEN 1 END) as current_season_matches"
echo "   FROM players p"
echo "   LEFT JOIN match_scores ms ON ("
echo "       ms.home_player_1_id = p.tenniscores_player_id OR "
echo "       ms.home_player_2_id = p.tenniscores_player_id OR "
echo "       ms.away_player_1_id = p.tenniscores_player_id OR "
echo "       ms.away_player_2_id = p.tenniscores_player_id"
echo "   )"
echo "   WHERE p.first_name = 'Ross' AND p.last_name = 'Freedman'"
echo "   GROUP BY p.id, p.first_name, p.last_name, p.tenniscores_player_id"
echo "   ORDER BY total_matches DESC;"
echo "   \""
echo ""
echo "7. Test the analyze-me page:"
echo "   https://rally-staging.up.railway.app/mobile/analyze-me"
echo ""
echo "=== END COMMANDS ===" 